name: indowira
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.0.0
  go_router: ^14.1.2
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.1
  hive_flutter: ^1.1.0
  freezed: ^2.1.1
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  overlay_support: ^2.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen: ^5.5.0+1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/svgs/
